services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend