services:
  frontend:
    image: "marcusacheema/frontend:latest"
    ports:
      - "3000:3000"

  backend:
    image: "marcusacheema/backend:latest"
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend